In [1]:
people ={ 
      'first': ["Corey","Anand","Ashish"],
    'last'  : ["Schafar" ,"Jaiswal","Jaiswal"],
    'email' : ["corey@gmail.com" ,"anand@gmail.com","ashish@gmail.com"]
}

In [2]:
import pandas as pd
df =pd.DataFrame(people)
df

    first     last             email
0   Corey  Schafar   corey@gmail.com
1   Anand  Jaiswal   anand@gmail.com
2  Ashish  Jaiswal  ashish@gmail.com

In [3]:
# adding new column in a dataframe

In [4]:
full_name =df['first']+" "+df['last']
df['fullname']=full_name
df

    first     last             email        fullname
0   Corey  Schafar   corey@gmail.com   Corey Schafar
1   Anand  Jaiswal   anand@gmail.com   Anand Jaiswal
2  Ashish  Jaiswal  ashish@gmail.com  Ashish Jaiswal

In [5]:
# deleting columns in a dataframe

In [6]:
df.drop(columns =['first','last'])

              email        fullname
0   corey@gmail.com   Corey Schafar
1   anand@gmail.com   Anand Jaiswal
2  ashish@gmail.com  Ashish Jaiswal

In [7]:
# if we want to make this change permanent use inplace =True

In [8]:
# spliting parts of a string

In [9]:
df['fullname'].str.split(' ')

0     [Corey, Schafar]
1     [Anand, Jaiswal]
2    [Ashish, Jaiswal]
Name: fullname, dtype: object

In [10]:
# adding these splited values as two new columns in a dataframe

In [11]:
df['fullname'].str.split(' ',expand =True) # this makes columns of splitted values

        0        1
0   Corey  Schafar
1   Anand  Jaiswal
2  Ashish  Jaiswal

In [12]:
df[['first','last']]=df['fullname'].str.split(' ',expand =True)

In [13]:
df

    first     last             email        fullname
0   Corey  Schafar   corey@gmail.com   Corey Schafar
1   Anand  Jaiswal   anand@gmail.com   Anand Jaiswal
2  Ashish  Jaiswal  ashish@gmail.com  Ashish Jaiswal

In [14]:
# adding rows   -  use concat function - it can concat rows as well as two dataframes

In [15]:
new_row =pd.DataFrame([{'first':'Bruce'}])
df=pd.concat([df,new_row],ignore_index=True)

In [16]:
df

    first     last             email        fullname
0   Corey  Schafar   corey@gmail.com   Corey Schafar
1   Anand  Jaiswal   anand@gmail.com   Anand Jaiswal
2  Ashish  Jaiswal  ashish@gmail.com  Ashish Jaiswal
3   Bruce      NaN               NaN             NaN

In [20]:
#Joining two dataframe end to end to make a new DataFrame

In [17]:
people ={ 
      'first': ["Steve","Tony"],
    'last'  : ["Rogers" ,"Stark"],
    'email' : ["cap@gmail.com" ,"ironman@gmail.com"]
}
df1 =pd.DataFrame(people)

In [48]:
#vertical concatenation - i.e, joining by rows
df2 =pd.concat([df,df1],ignore_index = True)  
# here ignore index helps to reorder indices according

In [19]:
df2

    first     last              email        fullname
0   Corey  Schafar    corey@gmail.com   Corey Schafar
1   Anand  Jaiswal    anand@gmail.com   Anand Jaiswal
2  Ashish  Jaiswal   ashish@gmail.com  Ashish Jaiswal
3   Bruce      NaN                NaN             NaN
4   Steve   Rogers      cap@gmail.com             NaN
5    Tony    Stark  ironman@gmail.com             NaN

In [37]:
#horizontal concatenation - joining by columns
df3=pd.concat([df,df1],axis='columns')  # we can also use axis =1 to join by column ,axis=0 → stack rows (default)axis=1 → add columns side-by-side.

In [38]:
df3

,first,last,email,fullname,first,last,email
0,Corey,Schafar,corey@gmail.com,Corey Schafar,Steve,Rogers,cap@gmail.com
1,Anand,Jaiswal,anand@gmail.com,Anand Jaiswal,Tony,Stark,ironman@gmail.com
2,Ashish,Jaiswal,ashish@gmail.com,Ashish Jaiswal,NaN,NaN,NaN
3,Bruce,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# removing rows from dataframe

In [39]:
df3.drop(index=3)

,first,last,email,fullname,first,last,email
0,Corey,Schafar,corey@gmail.com,Corey Schafar,Steve,Rogers,cap@gmail.com
1,Anand,Jaiswal,anand@gmail.com,Anand Jaiswal,Tony,Stark,ironman@gmail.com
2,Ashish,Jaiswal,ashish@gmail.com,Ashish Jaiswal,NaN,NaN,NaN

In [45]:
#df3.drop(index =df3[df3['last']=='Jaiswal'].index)  # cannot remove from df having duplicate column names

In [47]:
df.drop(index = df[df['last']=='Jaiswal'].index)

   first     last            email       fullname
0  Corey  Schafar  corey@gmail.com  Corey Schafar
3  Bruce      NaN              NaN            NaN