In [1]:
people ={ 
      'first': ["Corey","Anand","Ashish" ,"Prateek"],
    'last'  : ["Schafar" ,"Jaiswal","Jaiswal","Rastogi"],
    'email' : ["corey@gmail.com" ,"anand@gmail.com","ashish@gmail.com","rastogi@gmail.com"]
}

In [2]:
import pandas as pd
df =pd.DataFrame(people)
df

     first     last              email
0    Corey  Schafar    corey@gmail.com
1    Anand  Jaiswal    anand@gmail.com
2   Ashish  Jaiswal   ashish@gmail.com
3  Prateek  Rastogi  rastogi@gmail.com

In [3]:
df.sort_values('last')

     first     last              email
1    Anand  Jaiswal    anand@gmail.com
2   Ashish  Jaiswal   ashish@gmail.com
3  Prateek  Rastogi  rastogi@gmail.com
0    Corey  Schafar    corey@gmail.com

In [4]:
df

     first     last              email
0    Corey  Schafar    corey@gmail.com
1    Anand  Jaiswal    anand@gmail.com
2   Ashish  Jaiswal   ashish@gmail.com
3  Prateek  Rastogi  rastogi@gmail.com

In [5]:
df.sort_values('last',ascending =False)

     first     last              email
0    Corey  Schafar    corey@gmail.com
3  Prateek  Rastogi  rastogi@gmail.com
1    Anand  Jaiswal    anand@gmail.com
2   Ashish  Jaiswal   ashish@gmail.com

In [14]:
df.sort_values(by=['last','first'] ,ascending =False)

     first     last              email
0    Corey  Schafar    corey@gmail.com
3  Prateek  Rastogi  rastogi@gmail.com
2   Ashish  Jaiswal   ashish@gmail.com
1    Anand  Jaiswal    anand@gmail.com

In [15]:
df.sort_values(['last','first'] ,ascending =False)

     first     last              email
0    Corey  Schafar    corey@gmail.com
3  Prateek  Rastogi  rastogi@gmail.com
2   Ashish  Jaiswal   ashish@gmail.com
1    Anand  Jaiswal    anand@gmail.com

In [9]:
df =df.sort_values(['last','first'] ,ascending =[False ,True] )

In [10]:
df

     first     last              email
0    Corey  Schafar    corey@gmail.com
3  Prateek  Rastogi  rastogi@gmail.com
1    Anand  Jaiswal    anand@gmail.com
2   Ashish  Jaiswal   ashish@gmail.com

In [8]:
df.sort_index()

     first     last              email
0    Corey  Schafar    corey@gmail.com
1    Anand  Jaiswal    anand@gmail.com
2   Ashish  Jaiswal   ashish@gmail.com
3  Prateek  Rastogi  rastogi@gmail.com

In [11]:
df['last'].sort_values()

1    Jaiswal
2    Jaiswal
3    Rastogi
0    Schafar
Name: last, dtype: str